from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from app.ingestion.loaders import DocumentLoader
from app.ingestion.models import FinancialDocumentMetadata
from app.ingestion.splitter import DocumentSplitter
from app.vector_store import VectorStore


@dataclass(frozen=True, slots=True)
class IngestionResult:
    """
    Summary of one document-ingestion operation.
    """

    document_id: str
    source: str
    loaded_documents: int
    generated_chunks: int
    stored_vectors: int
    vector_ids: tuple[str, ...]


class IngestionPipeline:
    """
    Orchestrate the Sentinel-AI financial-document ingestion workflow.
    """

    def __init__(
        self,
        *,
        loader: DocumentLoader | None = None,
        splitter: DocumentSplitter | None = None,
        vector_store: VectorStore | None = None,
    ) -> None:
        self.loader = loader or DocumentLoader()
        self.splitter = splitter or DocumentSplitter()
        self.vector_store = vector_store or VectorStore()

    def ingest_file(
        self,
        path: str | Path,
        *,
        metadata: FinancialDocumentMetadata,
    ) -> IngestionResult:
        source_path = Path(path)

        loaded_documents = self.loader.load(
            source_path,
            metadata=metadata,
        )

        if not loaded_documents:
            raise ValueError(
                f"No readable content was extracted from: "
                f"{source_path}"
            )

        chunks = self.splitter.split(
            loaded_documents
        )

        if not chunks:
            raise ValueError(
                f"No retrieval chunks were generated from: "
                f"{source_path}"
            )

        self._validate_chunk_provenance(
            chunks,
            expected_document_id=metadata.document_id,
        )

        chunks = self._deduplicate_chunks(chunks)

        if not chunks:
            raise ValueError(
                "No unique chunks remain after deduplication."
            )

        vector_ids = self.vector_store.add_documents(
            chunks
        )

        if len(vector_ids) != len(chunks):
            raise RuntimeError(
                "Vector-store insertion count does not match "
                "the number of generated chunks."
            )

        return IngestionResult(
            document_id=metadata.document_id,
            source=metadata.source,
            loaded_documents=len(loaded_documents),
            generated_chunks=len(chunks),
            stored_vectors=len(vector_ids),
            vector_ids=tuple(vector_ids),
        )

    @staticmethod
    def _deduplicate_chunks(
        documents: list[Any],
    ) -> list[Any]:
        """
        Remove duplicate chunks within the current ingestion batch.

        The stable chunk_id is the provenance key generated by the
        document splitter.
        """

        seen: set[str] = set()
        unique_documents: list[Any] = []

        for document in documents:
            chunk_id = document.metadata.get(
                "chunk_id"
            )

            if not chunk_id:
                raise ValueError(
                    "Every ingestion chunk must contain "
                    "a stable chunk_id."
                )

            if chunk_id in seen:
                continue

            seen.add(chunk_id)
            unique_documents.append(document)

        return unique_documents

    @staticmethod
    def _validate_chunk_provenance(
        documents: list[Any],
        *,
        expected_document_id: str,
    ) -> None:
        for index, document in enumerate(documents):
            document_id = document.metadata.get(
                "document_id"
            )

            if document_id != expected_document_id:
                raise ValueError(
                    "Chunk provenance mismatch at index "
                    f"{index}: expected document_id="
                    f"'{expected_document_id}', received="
                    f"'{document_id}'."
                )

            chunk_id = document.metadata.get(
                "chunk_id"
            )

            if not chunk_id:
                raise ValueError(
                    f"Chunk at index {index} is missing "
                    "its chunk_id provenance."
                )