from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException

from app.api.explanation_schemas import (
    ExplanationRequest,
    ExplanationResponse,
)
from app.explanation.evidence import EvidenceSet
from app.explanation.pipeline import (
    GroundedExplanationPipeline,
)
from app.explanation.risk_output import RiskOutput
from app.explanation.service import (
    GroundedExplanationService,
)
from app.explanation.validator import (
    GroundednessValidator,
)
from app.explanation.dependencies import (
    get_explanation_service,
)


router = APIRouter(
    prefix="/explanations",
    tags=["explanations"],
)


def get_explanation_pipeline(
    service: GroundedExplanationService = Depends(
        get_explanation_service
    ),
) -> GroundedExplanationPipeline:
    """
    Construct the grounded explanation pipeline.
    """

    return GroundedExplanationPipeline(
        explanation_service=service,
        validator=GroundednessValidator(),
    )


@router.post(
    "",
    response_model=ExplanationResponse,
)
def create_explanation(
    request: ExplanationRequest,
    pipeline: GroundedExplanationPipeline = Depends(
        get_explanation_pipeline
    ),
) -> ExplanationResponse:
    """
    Generate and validate a grounded explanation.

    The supplied risk result is explained using only the supplied
    evidence. No market prediction or investment recommendation
    is generated by this endpoint.
    """

    risk_output = RiskOutput(
        risk_score=request.risk_output.risk_score,
        risk_label=request.risk_output.risk_label,
        model_name=request.risk_output.model_name,
        model_version=request.risk_output.model_version,
        metadata=request.risk_output.metadata,
    )

    evidence = EvidenceSet.from_sequence(
        request.evidence
    )

    try:
        result = pipeline.explain(
            risk_output=risk_output,
            evidence=evidence,
        )

    except ValueError as exc:
        raise HTTPException(
            status_code=422,
            detail=str(exc),
        ) from exc

    except RuntimeError as exc:
        raise HTTPException(
            status_code=503,
            detail=str(exc),
        ) from exc

    return ExplanationResponse(
        explanation=result.explanation,
        model=result.model,
        provider=result.provider,
        evidence_count=result.evidence_count,
        citations=list(result.citations),
    )