from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, field_validator


class SentimentLabel(StrEnum):
    """Financial-news sentiment labels."""

    NEGATIVE = "negative"
    NEUTRAL = "neutral"
    POSITIVE = "positive"


class NewsArticle(BaseModel):
    """
    Canonical financial-news data contract.

    The article timestamp represents when the information is
    considered available to the research pipeline.

    Sentiment labels are research dataset labels. They are not
    generated by the LLM.
    """

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
    )

    timestamp: datetime
    ticker: str = Field(
        min_length=1,
        max_length=10,
    )
    headline: str = Field(
        min_length=1,
        max_length=500,
    )
    text: str = Field(
        min_length=1,
        max_length=10_000,
    )
    source: str = Field(
        min_length=1,
        max_length=200,
    )
    sentiment_label: SentimentLabel

    @field_validator("ticker")
    @classmethod
    def normalize_ticker(cls, value: str) -> str:
        """Normalize ticker identifiers."""

        normalized = value.strip().upper()

        if not normalized:
            raise ValueError(
                "ticker cannot be empty"
            )

        return normalized

    @field_validator(
        "headline",
        "text",
        "source",
    )
    @classmethod
    def normalize_text(cls, value: str) -> str:
        """Normalize surrounding whitespace."""

        normalized = " ".join(
            value.split()
        )

        if not normalized:
            raise ValueError(
                "text fields cannot be empty"
            )

        return normalized


class NewsDataset(BaseModel):
    """Validated collection of financial-news articles."""

    model_config = ConfigDict(
        extra="forbid",
    )

    articles: list[NewsArticle] = Field(
        min_length=1,
    )

    @property
    def size(self) -> int:
        """Return the number of articles."""

        return len(self.articles)

    @property
    def tickers(self) -> list[str]:
        """Return unique tickers in deterministic order."""

        return sorted(
            {
                article.ticker
                for article in self.articles
            }
        )

    def by_ticker(
        self,
        ticker: str,
    ) -> list[NewsArticle]:
        """Return articles belonging to a ticker."""

        normalized = ticker.strip().upper()

        return [
            article
            for article in self.articles
            if article.ticker == normalized
        ]